import Stock from "../../types/Stock";

export const stocks: Stock[] = [
  {
    ticker: "AACG",
    name: "ATA Creativity Global American Depositary Shares",
    market: "stocks",
    locale: "us",
    primary_exchange: "XNAS",
    type: "ADRC",
    active: true,
    currency_name: "usd",
    cik: "0001420529",
    composite_figi: "BBG000V2S3P6",
    share_class_figi: "BBG001T125S9",
    last_updated_utc: "2024-05-17T00:00:00Z",
  },
  {
    ticker: "AADI",
    name: "Aadi Bioscience, Inc. Common Stock",
    market: "stocks",
    locale: "us",
    primary_exchange: "XNAS",
    type: "CS",
    active: true,
    currency_name: "usd",
    cik: "0001422142",
    composite_figi: "BBG002WN7DT2",
    share_class_figi: "BBG002WN7DV9",
    last_updated_utc: "2024-11-01T00:00:00Z",
  },
  {
    ticker: "AADR",
    name: "AdvisorShares Dorsey Wright ADR ETF",
    market: "stocks",
    locale: "us",
    primary_exchange: "XNAS",
    type: "ETF",
    active: true,
    currency_name: "usd",
    composite_figi: "BBG000BDYRW6",
    share_class_figi: "BBG001T9B1Y4",
    last_updated_utc: "2024-08-20T00:00:00Z",
  },
  {
    ticker: "AAL",
    name: "American Airlines Group Inc.",
    market: "stocks",
    locale: "us",
    primary_exchange: "XNAS",
    type: "CS",
    active: true,
    currency_name: "usd",
    cik: "0000006201",
    composite_figi: "BBG005P7Q881",
    share_class_figi: "BBG005P7Q907",
    last_updated_utc: "2024-05-17T00:00:00Z",
  },
  {
    ticker: "AAME",
    name: "Atlantic American Corp",
    market: "stocks",
    locale: "us",
    primary_exchange: "XNAS",
    type: "CS",
    active: true,
    currency_name: "usd",
    cik: "0000008177",
    composite_figi: "BBG000B9XB24",
    share_class_figi: "BBG001S5N8T1",
    last_updated_utc: "2024-11-01T00:00:00Z",
  },
  {
    ticker: "AAOI",
    name: "Applied Optoelectronics, Inc.",
    market: "stocks",
    locale: "us",
    primary_exchange: "XNAS",
    type: "CS",
    active: true,
    currency_name: "usd",
    cik: "0001158114",
    composite_figi: "BBG000D6VW15",
    share_class_figi: "BBG001SG47G4",
    last_updated_utc: "2024-11-01T00:00:00Z",
  },
  {
    ticker: "AAON",
    name: "Aaon Inc",
    market: "stocks",
    locale: "us",
    primary_exchange: "XNAS",
    type: "CS",
    active: true,
    currency_name: "usd",
    cik: "0000824142",
    composite_figi: "BBG000C2LZP3",
    share_class_figi: "BBG001S6CZK0",
    last_updated_utc: "2024-05-17T00:00:00Z",
  },
  {
    ticker: "AAPB",
    name: "GraniteShares ETF Trust GraniteShares 2x Long AAPL Daily ETF",
    market: "stocks",
    locale: "us",
    primary_exchange: "XNAS",
    type: "ETS",
    active: true,
    currency_name: "usd",
    composite_figi: "BBG0193F21N2",
    share_class_figi: "BBG0193F22H7",
    last_updated_utc: "2024-11-01T00:00:00Z",
  },
  {
    ticker: "AAPD",
    name: "Direxion Daily AAPL Bear 1X Shares",
    market: "stocks",
    locale: "us",
    primary_exchange: "XNAS",
    type: "ETS",
    active: true,
    currency_name: "usd",
    composite_figi: "BBG0193YGJ57",
    share_class_figi: "BBG0193YGK09",
    last_updated_utc: "2024-11-01T00:00:00Z",
  },
  {
    ticker: "AAPL",
    name: "Apple Inc.",
    market: "stocks",
    locale: "us",
    primary_exchange: "XNAS",
    type: "CS",
    active: true,
    currency_name: "usd",
    cik: "0000320193",
    composite_figi: "BBG000B9XRY4",
    share_class_figi: "BBG001S5N8V8",
    last_updated_utc: "2024-11-01T00:00:00Z",
  },
];
